### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by sahar-hajijafari** [marija-stanojevic/diabetes-complications-prediction-2020#1]
Hi, thanks for your description.
I can't find the dataset. can you help me to find it?
I need a link to download the dataset.
thank you

**Comment by marija-stanojevic** [comment]
Hello,

thank you for your message. I never got notified and I only saw it now accidentally. Unfortunately, we cannot share the dataset due to the privacy of EHR DATA. We shared code to help other scientist develop similar tools on their datasets
